cms_app/urls.py
from django.urls import path
from .views import CmsUsersView,cms_overview_view, cms_view, cms_categories_view, CMSDashboardView

app_name = 'cms_app'

urlpatterns = [
    path("dashboard", cms_overview_view, name="cms_overview_view"),  # Correct name
    path('', CMSDashboardView.as_view(), name='cms_dashboard'),
    path('users', CmsUsersView.as_view(), name='cms_users_view'),
    path('settings', cms_view, name='cms_view'),
    path('categories', cms_categories_view, name='cms_categories_view'),
]

community_board_project/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('profile/', include('profile_app.urls')),
    path('cms/', include('cms_app.urls')),
    path('accounts/', include('allauth.urls')),
    path('', include('community_board_app.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

cms_app/models.py
from django.db import models
from django.core.cache import cache  # Import cache
from django.core.exceptions import ValidationError
from django.utils import timezone
from django.contrib.auth.models import User

class WebsiteSettings(models.Model):
    primary_color = models.CharField(max_length=7, default="#3498db")  # Hex color
    secondary_color = models.CharField(max_length=7, default="#2c3e50")  # Hex color
    
    button_color = models.CharField(max_length=7, default="#3498db")  # Hex color
    button_text_color = models.CharField(max_length=7, default="#ffffff")  # Hex color
    button_hover_color = models.CharField(max_length=7, default="#2980b9")  # Hex color
    button_hover_text_color = models.CharField(max_length=7, default="#ffffff")  # Hex color

    def save(self, *args, **kwargs):
        if WebsiteSettings.objects.exists() and not self.pk:
            raise ValidationError("Only one instance of WebsiteSettings is allowed.")
        super().save(*args, **kwargs)
        cache.clear()  # Clear cache to apply changes instantly

    def __str__(self):
        return "Website Settings"

    class Meta:
        verbose_name = "Website Setting"
        verbose_name_plural = "Website Settings"

class NavbarSettings(models.Model):
    site_title = models.CharField(max_length=255, default="My Site")
    logo = models.FileField(upload_to='navbar_icon/', blank=True, null=True)
    alt_text = models.CharField(max_length=255, blank=True, null=True)  # Alt text for the logo
    def __str__(self):
        return "Navbar Settings"

    class Meta:
        verbose_name_plural = "Navbar Settings"


class HeroSettings(models.Model):
    hero_active = models.BooleanField(default=False)
    hero_image = models.FileField(upload_to='images/', blank=True, null=True)
    text_color = models.CharField(max_length=7, default="#ffffff")  # Default color is white
    bg_color = models.CharField(max_length=7, default="#111827") # Default color is a dark blue
    button_one_text = models.CharField(max_length=255, blank=True, null=True)
    button_one_link = models.CharField(max_length=255, blank=True, null=True)
    button_two_text = models.CharField(max_length=255, blank=True, null=True)
    button_two_link = models.CharField(max_length=255, blank=True, null=True)
    h1_text = models.CharField(max_length=255, blank=True, null=True)
    sub_text = models.CharField(max_length=255, blank=True, null=True)

    featured_active = models.BooleanField(default=False)
    featured_one_icon = models.FileField(upload_to='icons/', blank=True, null=True)
    featured_one_link = models.CharField(max_length=255, blank=True, null=True)
    featured_two_icon = models.FileField(upload_to='icons/', blank=True, null=True)
    featured_two_link = models.CharField(max_length=255, blank=True, null=True)
    featured_three_icon = models.FileField(upload_to='icons/', blank=True, null=True)
    featured_three_link = models.CharField(max_length=255, blank=True, null=True)

    def __str__(self):
        return "Hero Section Settings"

    class Meta:
        verbose_name_plural = "Hero Settings"

cms_app/forms.py
# forms.py
from django import forms
from .models import NavbarSettings, HeroSettings, WebsiteSettings


class WebsiteSettingsForm(forms.ModelForm):
    class Meta:
        model = WebsiteSettings
        fields = ['primary_color', 'secondary_color', 'button_color', 'button_hover_color',
                  'button_text_color', 'button_hover_text_color']


        widgets = {
            'primary_color': forms.TextInput(attrs={'type': 'color'}),  # Adds a color picker
            'secondary_color': forms.TextInput(attrs={'type': 'color'}),  # Adds a color picker
            'button_color': forms.TextInput(attrs={'type': 'color'}),  # Adds a color picker
            'button_text_color': forms.TextInput(attrs={'type': 'color'}),  # Adds a color picker
            'button_hover_color': forms.TextInput(attrs={'type': 'color'}),  # Adds a color picker
            'button_hover_text_color': forms.TextInput(attrs={'type': 'color'}),  # Adds a color picker
        }

        

class NavbarSettingsForm(forms.ModelForm):
    class Meta:
        model = NavbarSettings
        fields = ['site_title', 'logo', 'alt_text']

        labels = {
            'site_title': 'Site Title',
            'logo': 'Site Logo',
            'alt_text': 'Logo alt text'
        }


class HeroSettingsForm(forms.ModelForm):
    class Meta:
        model = HeroSettings
        fields = ['hero_active', 'hero_image', 'text_color', 'bg_color', 'h1_text',
                  'sub_text', 'button_one_text', 'button_one_link',
                  'button_two_text', 'button_two_link', 'featured_active',
                  'featured_one_icon', 'featured_one_link', 'featured_two_icon',
                  'featured_two_link', 'featured_three_icon', 'featured_three_link']


        labels = {
            'hero_active': 'Activeate Hero Section',
            'bg_color': 'Background Color',
            'featured_active': 'Activate Featured Section',
        }


        widgets = {
            'bg_color': forms.TextInput(attrs={'type': 'color'}),  # Adds a color picker
            'text_color': forms.TextInput(attrs={'type': 'color'}),  # Adds a color picker
        }

cms_app/views.py
from django.shortcuts import render, redirect
from django.views.generic import TemplateView
from django.http import HttpRequest
from user_visit.models import UserVisit
from django.utils.timezone import now
from django.utils import timezone
from datetime import timedelta

from cms_app.models import (
    NavbarSettings, HeroSettings,
    WebsiteSettings
    )

from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.decorators import login_required
from django.http import HttpResponseForbidden

from profile_app.models import User
from community_board_app.models import Category
from cms_app.forms import NavbarSettingsForm, HeroSettingsForm, WebsiteSettingsForm
from django.views import View
from django.urls import reverse
from django.db.models import Count



class CMSDashboardView(LoginRequiredMixin, TemplateView):
    template_name = "cms_app/cms_dashboard.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["current_view"] = self.request.resolver_match.view_name  # Get the current view name
        return context
    


@login_required
def cms_overview_view(request: HttpRequest):
    # If not authenticated, return 403 Forbidden
    if not request.user.is_authenticated:
        return HttpResponseForbidden("You do not have permission to view this page.")

    if request.headers.get('HX-Request'):
        return render(request, 'cms_app/partials/cms_overview.html')

    return render(request, 'cms_app/cms_dashboard.html', {'current_view': 'cms_overview_view'})



# CMS settings view
def cms_view(request):
    # Check if the user is authenticated, otherwise return a 403 Forbidden response
    if not request.user.is_authenticated:
        return HttpResponseForbidden("You do not have permission to view this page.")
    
    navbar_settings, created_navbar = NavbarSettings.objects.get_or_create(pk=1)
    hero_settings, created_hero = HeroSettings.objects.get_or_create(pk=1)
    website_settings, created_website = WebsiteSettings.objects.get_or_create(pk=1)

    if request.method == 'POST':
        navbar_form = NavbarSettingsForm(request.POST, request.FILES, instance=navbar_settings)
        hero_form = HeroSettingsForm(request.POST, request.FILES, instance=hero_settings)
        website_form = WebsiteSettingsForm(request.POST, request.FILES, instance=website_settings)

        if navbar_form.is_valid() and hero_form.is_valid() and website_form.is_valid():
            navbar_form.save()
            hero_form.save()
            website_form.save()

            if request.headers.get('HX-Request'):
                return render(request, 'cms_app/partials/cms_site_settings.html', {
                    'navbar_form': navbar_form,
                    'hero_form': hero_form,
                    'website_form': website_form
                })

            return redirect(reverse('cms_app:cms_dashboard'))

    else:
        navbar_form = NavbarSettingsForm(instance=navbar_settings)
        hero_form = HeroSettingsForm(instance=hero_settings)
        website_form = WebsiteSettingsForm(instance=website_settings)

    if request.headers.get('HX-Request'):
        return render(request, 'cms_app/partials/cms_site_settings.html', {
            'navbar_form': navbar_form,
            'hero_form': hero_form,
            'website_form': website_form
        })

    return render(request, 'cms_app/cms_dashboard.html', {
        'navbar_form': navbar_form,
        'hero_form': hero_form,
        'website_form': website_form,
        'current_view': 'cms_view'
    })



class CmsUsersView(LoginRequiredMixin, View):
    model = User
    paginate_by = 50 
    
    def get(self, request: HttpRequest):
        # Query all users with their related profiles
        users = User.objects.all().select_related('profile')

        # Get the current time
        now = timezone.now()

        # Check if the user is online
        for user in users:
            # Consider user online if their last_seen is within the last 5 minutes
            user.is_online = user.profile.last_seen and now - user.profile.last_seen < timedelta(minutes=5)

        # If it's an HTMX request, return only the partial template
        if request.headers.get('HX-Request'):
            return render(request, 'cms_app/partials/cms_users.html', {'users': users})

        # For normal requests, return the full dashboard template
        return render(request, 'cms_app/cms_dashboard.html', {
            'current_view': 'cms_users_view',
            'users': users,
        })


@login_required
def cms_categories_view(request: HttpRequest):
    # Annotate categories with the number of related posts
    categories = Category.objects.annotate(post_count=Count('posts'))

    # Check if the user is authenticated; if not, return 403 Forbidden
    if not request.user.is_authenticated:
        return HttpResponseForbidden("You do not have permission to view this page.")

    # Handle HTMX requests by returning only the partial template
    if request.headers.get("HX-Request"):
        return render(request, "cms_app/partials/cms_categories.html", {"categories": categories})

    # For normal requests, render the full dashboard template
    return render(
        request,
        "cms_app/cms_dashboard.html",
        {
            "current_view": "cms_categories_view",
            "categories": categories
        }
    )

cms_app/templates/cms_app/components/cms_sidenav.html
<button data-drawer-target="cta-button-sidebar" data-drawer-toggle="cta-button-sidebar"
   aria-controls="cta-button-sidebar" type="button"
   class="inline-flex items-center p-2 mt-2 ms-3 text-sm text-gray-500 rounded-lg sm:hidden hover:bg-gray-100 focus:outline-none focus:ring-2 focus:ring-gray-200 ">
   <span class="sr-only">Open sidebar</span>
   <svg class="w-6 h-6" aria-hidden="true" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg">
      <path clip-rule="evenodd" fill-rule="evenodd"
         d="M2 4.75A.75.75 0 012.75 4h14.5a.75.75 0 010 1.5H2.75A.75.75 0 012 4.75zm0 10.5a.75.75 0 01.75-.75h7.5a.75.75 0 010 1.5h-7.5a.75.75 0 01-.75-.75zM2 10a.75.75 0 01.75-.75h14.5a.75.75 0 010 1.5H2.75A.75.75 0 012 10z">
      </path>
   </svg>
</button>

<aside id="cta-button-sidebar"
   class="fixed top-24 left-0 z-40 w-64 h-screen transition-transform -translate-x-full sm:translate-x-0"
   aria-label="Sidebar">
   <div class="h-full px-3 py-4 overflow-y-auto">
      <ul class="space-y-2 font-medium">

         <li>
            <a hx-get="{% url 'cms_app:cms_overview_view' %}" hx-target="#cms-content" hx-swap="innerHTML"
               hx-trigger="click" hx-push-url="true"
               class="cursor-pointer flex items-center p-2 text-gray-800 rounded-lg hover:bg-gray-100 group">
               <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="none" stroke="currentColor"
                  stroke-linecap="round" stroke-linejoin="round" width="28" height="28" stroke-width="1.75">
                  <path d="M10 3.2a9 9 0 1 0 10.8 10.8a1 1 0 0 0 -1 -1h-6.8a2 2 0 0 1 -2 -2v-7a.9 .9 0 0 0 -1 -.8">
                  </path>
                  <path d="M15 3.5a9 9 0 0 1 5.5 5.5h-4.5a1 1 0 0 1 -1 -1v-4.5"></path>
               </svg>
               <span class="flex-1 ms-3 whitespace-nowrap">Dashboard</span>
            </a>
         </li>
         <li>
            <a href="#" class="line-through flex items-center p-2 text-gray-800 rounded-lg hover:bg-gray-100 group">
               <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="none" stroke="currentColor"
                  stroke-linecap="round" stroke-linejoin="round" width="28" height="28" stroke-width="1.75">
                  <path d="M10 21v-6.5a3.5 3.5 0 0 0 -7 0v6.5h18v-6a4 4 0 0 0 -4 -4h-10.5"></path>
                  <path d="M12 11v-8h4l2 2l-2 2h-4"></path>
                  <path d="M6 15h1"></path>
               </svg>
               <span class="flex-1 ms-3 whitespace-nowrap">Inbox</span>
               <span
                  class="inline-flex items-center justify-center w-3 h-3 p-3 ms-3 text-sm font-medium text-blue-800 bg-blue-100 rounded-full">3</span>
            </a>
         </li>
         <li>
            <a hx-get="{% url 'cms_app:cms_users_view' %}" hx-target="#cms-content" hx-swap="innerHTML"
               hx-trigger="click" hx-push-url="true"
               class="cursor-pointer flex items-center p-2 text-gray-800 rounded-lg  hover:bg-gray-100 group">
               <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="none" stroke="currentColor"
                  stroke-linecap="round" stroke-linejoin="round" width="28" height="28" stroke-width="1.75">
                  <path d="M10 13a2 2 0 1 0 4 0a2 2 0 0 0 -4 0"></path>
                  <path d="M8 21v-1a2 2 0 0 1 2 -2h4a2 2 0 0 1 2 2v1"></path>
                  <path d="M15 5a2 2 0 1 0 4 0a2 2 0 0 0 -4 0"></path>
                  <path d="M17 10h2a2 2 0 0 1 2 2v1"></path>
                  <path d="M5 5a2 2 0 1 0 4 0a2 2 0 0 0 -4 0"></path>
                  <path d="M3 13v-1a2 2 0 0 1 2 -2h2"></path>
               </svg>
               <span class="flex-1 ms-3 whitespace-nowrap">Users</span>
            </a>
         </li>
         <li>
            <a hx-get="{% url 'cms_app:cms_categories_view' %}" hx-target="#cms-content" hx-swap="innerHTML"
               hx-trigger="click" hx-push-url="true"
               class="cursor-pointer flex items-center p-2 text-gray-800 rounded-lg hover:bg-gray-100 group">
               <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="none" stroke="currentColor"
                  stroke-linecap="round" stroke-linejoin="round" width="28" height="28" stroke-width="1.75">
                  <path d="M14 4h6v6h-6z"></path>
                  <path d="M4 14h6v6h-6z"></path>
                  <path d="M17 17m-3 0a3 3 0 1 0 6 0a3 3 0 1 0 -6 0"></path>
                  <path d="M7 7m-3 0a3 3 0 1 0 6 0a3 3 0 1 0 -6 0"></path>
               </svg>
               <span class="ms-3">Categories</span>
            </a>

         </li>
         <li>
            <a hx-get="{% url 'cms_app:cms_view' %}" hx-target="#cms-content" hx-swap="innerHTML" hx-trigger="click"
               hx-push-url="{% url 'cms_app:cms_view' %}"
               class="cursor-pointer flex items-center p-2 text-gray-800 rounded-lg hover:bg-gray-100 group">
               <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="none" stroke="currentColor"
                  stroke-linecap="round" stroke-linejoin="round" width="28" height="28" stroke-width="1.75">
                  <path d="M14 6m-2 0a2 2 0 1 0 4 0a2 2 0 1 0 -4 0"></path>
                  <path d="M4 6l8 0"></path>
                  <path d="M16 6l4 0"></path>
                  <path d="M8 12m-2 0a2 2 0 1 0 4 0a2 2 0 1 0 -4 0"></path>
                  <path d="M4 12l2 0"></path>
                  <path d="M10 12l10 0"></path>
                  <path d="M17 18m-2 0a2 2 0 1 0 4 0a2 2 0 1 0 -4 0"></path>
                  <path d="M4 18l11 0"></path>
                  <path d="M19 18l1 0"></path>
               </svg>
               <span class="ms-3">Site Settings</span>
            </a>
         </li>
         {% if user.is_authenticated %}

         <li>
            <a href="{% url 'account_logout' %}"
               class="flex items-center p-2 text-gray-800 rounded-lg  hover:bg-gray-100 group">
               <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="none" stroke="currentColor"
                  stroke-linecap="round" stroke-linejoin="round" width="28" height="28" stroke-width="1.75">
                  <path d="M10 8v-2a2 2 0 0 1 2 -2h7a2 2 0 0 1 2 2v12a2 2 0 0 1 -2 2h-7a2 2 0 0 1 -2 -2v-2"></path>
                  <path d="M15 12h-12l3 -3"></path>
                  <path d="M6 15l-3 -3"></path>
               </svg>
               <span class="flex-1 ms-3 whitespace-nowrap">Log Out</span>
            </a>
         </li>
         {% else %}
         <li>
            <a href="{% url 'account_login' %}"
               class="flex items-center p-2 text-gray-800 rounded-lg  hover:bg-gray-100 group">
               <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="none" stroke="currentColor"
                  stroke-linecap="round" stroke-linejoin="round" width="28" height="28" stroke-width="1.75">
                  <path d="M9 8v-2a2 2 0 0 1 2 -2h7a2 2 0 0 1 2 2v12a2 2 0 0 1 -2 2h-7a2 2 0 0 1 -2 -2v-2"></path>
                  <path d="M3 12h13l-3 -3"></path>
                  <path d="M13 15l3 -3"></path>
               </svg>
               <span class="flex-1 ms-3 whitespace-nowrap">Log In</span>
            </a>
         </li>
         {% endif %}
         <div id="dropdown-cta" class="p-4 mt-6 rounded-lg bg-blue-50 " role="alert">
            <div class="flex items-center mb-3">
               <span
                  class="bg-orange-100 text-orange-800 text-sm font-semibold me-2 px-2.5 py-0.5 rounded-sm ">Beta</span>
               <button type="button"
                  class="ms-auto -mx-1.5 -my-1.5 bg-blue-50 inline-flex justify-center items-center w-6 h-6 text-blue-900 rounded-lg focus:ring-2 focus:ring-blue-400 p-1 hover:bg-blue-200 :bg-blue-900"
                  data-dismiss-target="#dropdown-cta" aria-label="Close"
                  hx-on:click="localStorage.setItem('dropdown-cta-dismissed', 'true'); this.closest('#dropdown-cta').remove()">
                  <span class="sr-only">Close</span>
                  <svg class="w-2.5 h-2.5" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="none"
                     viewBox="0 0 14 14">
                     <path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2"
                        d="m1 1 6 6m0 0 6 6M7 7l6-6M7 7l-6 6" />
                  </svg>
               </button>
            </div>
            <p class="mb-3 text-sm text-blue-800">
               Preview the new CMS dashboard navigation! This project is in beta—built with Django, featuring a template
               message board and a CMS for site administrators and users.
            </p>
         </div>
   </div>
</aside>