cms_app/urls.py
from django.urls import path
from .views import CmsUsersView,cms_overview_view, cms_view, cms_categories_view, CMSDashboardView

app_name = 'cms_app'

urlpatterns = [
    path("dashboard", cms_overview_view, name="cms_overview_view"),  # Correct name
    path('', CMSDashboardView.as_view(), name='cms_dashboard'),
    path('users', CmsUsersView.as_view(), name='cms_users_view'),
    path('settings', cms_view, name='cms_view'),
    path('categories', cms_categories_view, name='cms_categories_view'),
]

community_board_app/urls.py
from django.urls import path
from . import views
from .views import (
    IndexListView,
    PostListView, PostDetailView,
    CreatePostView, PostDeleteView,
    PostUpdateView, CommentDeleteView,
    CategoryListView, CategoryDetailView,
    CategoryDeleteView
)
app_name = 'community_board_app'

urlpatterns = [
    # path('', index, name='index'),
    path('', IndexListView.as_view(), name='index'),
    path('posts/', PostListView.as_view(), name='post_list'),
    path('create/', CreatePostView.as_view(), name='create_post'),
    path('post/<slug:slug>/', PostDetailView.as_view(), name='post_detail'),
    path('delete/<slug:slug>/', PostDeleteView.as_view(), name='delete_post'),
    path('edit/<slug:slug>/', PostUpdateView.as_view(), name='edit_post'),
    path('comment/<int:pk>/delete/', CommentDeleteView.as_view(), name='comment_delete'),
    path('categories/', CategoryListView.as_view(), name='category_list'),
    path('category/<slug:slug>/', CategoryDetailView.as_view(), name='category_detail'),
    path('delete/category/<slug:slug>/', CategoryDeleteView.as_view(), name='delete_category'),
]

community_board_project/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('profile/', include('profile_app.urls')),
    path('cms/', include('cms_app.urls')),
    path('accounts/', include('allauth.urls')),
    path('', include('community_board_app.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

profile_app/urls.py
from django.urls import path
from .views import profile, edit_profile

app_name = 'profile_app'

urlpatterns = [
    path('', profile, name='profile'),
    path('edit/', edit_profile, name='edit_profile'),
]

community_board_app/models.py
from django.db import models
from django.utils.text import slugify
from django.urls import reverse
from django.contrib.auth.models import User

class Category(models.Model):
    name = models.CharField(max_length=100, unique=True)  # Category name (e.g., "Technology", "Health")
    slug = models.SlugField(unique=True, blank=True)  # URL-friendly identifier
    description = models.TextField(blank=True, null=True)  # Optional description

    def __str__(self):
        return self.name

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(self.name)
        super().save(*args, **kwargs)

class Post(models.Model):
    DRAFT = 'draft'
    PUBLISHED = 'published'

    STATUS_CHOICES = [
        (DRAFT, 'Draft'),
        (PUBLISHED, 'Published'),
    ]

    title = models.CharField(max_length=200)
    content = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    author = models.ForeignKey('auth.User', on_delete=models.CASCADE, related_name='posts')  # Added related_name
    category = models.ForeignKey(Category, on_delete=models.SET_NULL, null=True, blank=True, related_name='posts')
    slug = models.SlugField(max_length=250, unique=True)
    status = models.CharField(max_length=10, choices=STATUS_CHOICES,default=DRAFT)

    class Meta:
        verbose_name_plural = "posts"
        ordering = ['-created_at'] 

    def save(self, *args, **kwargs):
        if not self.slug:  # Create slug only if it doesn't exist
            self.slug = slugify(self.title)
        super().save(*args, **kwargs)

    def __str__(self):
        return self.title
    
    def get_absolute_url(self):
        return reverse('community_board_app:post_detail', kwargs={'slug': self.slug})
    
    
class Comment(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE, related_name='comments')
    author = models.ForeignKey(User, on_delete=models.CASCADE)  # Assuming users are logged in
    email = models.EmailField(blank=True, null=True)
    content = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f'Comment by {self.author.username}'
    
    class Meta:
        ordering = ['created_at']

class Like(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE, related_name='likes')
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='likes')

    class Meta:
        constraints = [
            models.UniqueConstraint(fields=['post', 'user'], name='unique_post_like')
        ]

    def __str__(self):
        return f'{self.user.username} likes "{self.post.title}"'


class SiteDescription(models.Model):
    title = models.CharField(max_length=255)
    content = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    num_posts = models.PositiveIntegerField(default=0)
    num_members = models.PositiveIntegerField(default=0)


    def save(self, *args, **kwargs):
        """Ensure only one instance exists"""
        if not SiteDescription.objects.exists():
            super().save(*args, **kwargs)
        else:
            self.pk = SiteDescription.objects.first().pk
            super().save(*args, **kwargs)

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = "Site Description"
        verbose_name_plural = "Site Description"

    def num_posts(self):
        """Returns the number of published posts."""
        return Post.objects.filter(status=Post.PUBLISHED).count()

    def num_users(self):
        """Returns the total number of registered users."""
        return User.objects.count()

community_board_app/forms.py
from django import forms
from .models import Post, Comment

class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ['title', 'content', 'category','status']
        

        widgets = {
            'content': forms.Textarea(attrs={'placeholder': 'Write your post...'}),
        }


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ['content']
        
        labels = {
            'content': 'Comment'
        }

        widgets = {
            'content': forms.Textarea(attrs={'placeholder': 'Write your comment...'})
        }

community_board_app/views.py
from django.shortcuts import render
from django.http import HttpResponse
from django.http import JsonResponse
from django.views.generic import (
    DetailView, ListView,
    CreateView, DeleteView,
    UpdateView, 
)
from .models import Post, Comment, Category, SiteDescription

from django.shortcuts import get_object_or_404
from django.db.models import Count, Prefetch
from cms_app.models import HeroSettings
from .forms import PostForm, CommentForm
from django.shortcuts import redirect
from django.urls import reverse_lazy
from django.template.loader import render_to_string

from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin


from django.shortcuts import render
from django.http import HttpResponse
from django.template.loader import render_to_string


def index(request):
    return render(request, 'community_board_app/index.html')

class IndexListView(ListView):
    model = Category
    template_name = 'community_board_app/index.html'
    context_object_name = 'categories'

    def get_queryset(self):
        # Prefetch posts related to each category with status 'PUBLISHED' and annotated with comment count
        return Category.objects.prefetch_related(
            Prefetch(
                'posts',
                queryset=Post.objects.filter(status=Post.PUBLISHED).annotate(comment_count=Count('comments'))
            )
        ).all()

    def get_context_data(self, **kwargs):
        # Get the context data, which includes categories by default
        context = super().get_context_data(**kwargs)
        
        # Optionally add hero settings if needed
        context['hero_settings'] = HeroSettings.objects.first()  # Assuming only one object exists
        context['site'] = SiteDescription.objects.first()  # Fetch the single instance
        return context

class PostListView(ListView):
    model = Post
    template_name = 'community_board_app/post_list.html'
    context_object_name = 'posts'

    def get_queryset(self):
        return Post.objects.annotate(comment_count=Count('comments'))  # Ensure queryset includes comment count

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['posts'] = Post.objects.annotate(comment_count=Count('comments'))
        context['categories'] = Category.objects.all()
        context['hero_settings'] = get_object_or_404(HeroSettings, pk=1)
        return context

    def get(self, request, *args, **kwargs):
        if request.headers.get('Hx-Request'):  # HTMX request
            posts = self.get_queryset()
            html = render_to_string("community_board_app/partials/post_partial.html", {"posts": posts})  # Pass as a list
            return HttpResponse(html)

        return super().get(request, *args, **kwargs)


class CreatePostView(LoginRequiredMixin, UserPassesTestMixin, CreateView):
    model = Post
    form_class = PostForm
    template_name = 'community_board_app/post_form.html'  # Template for the form
    success_url = reverse_lazy('community_board_app:post_list')  # Redirect after success

    def test_func(self):
        user = self.request.user
        return user.is_authenticated or user.is_staff or user.is_superuser  # Allow if logged in OR is staff/superuser
    
    def form_valid(self, form):
        form.instance.author = self.request.user  # Assign the logged-in user
        self.object = form.save()
        return redirect('community_board_app:post_detail', slug=self.object.slug)  # Redirect to post detail
    

class PostDetailView(DetailView):
    model = Post
    template_name = 'community_board_app/post_detail.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        post = self.object
        context['form'] = CommentForm()
        context['comments'] = post.comments.all()  # Retrieve all comments related to the post
        return context

    def get_queryset(self):
        return Post.objects.annotate(comment_count=Count('comments'))

    def post(self, request, *args, **kwargs):
        post = self.get_object()  # Get the current post
        form = CommentForm(request.POST)
        if form.is_valid():
            # Save the comment, but don't commit it to the DB yet
            comment = form.save(commit=False)
            comment.post = post  # Link the comment to the current post
            comment.author = request.user  # Set the comment author to the current user
            comment.save()  # Now save the comment
            return redirect('community_board_app:post_detail', slug=post.slug)  # Redirect to the post's detail page

        # If the form is not valid, render the same template with errors
        return self.get(request, *args, **kwargs)


class PostUpdateView(LoginRequiredMixin, UserPassesTestMixin, UpdateView):
    model = Post
    form_class = PostForm
    template_name = 'community_board_app/edit_post.html'
    
    def test_func(self):
        post = self.get_object()
        if self.request.user == post.author:
            return True
        return False
    

class PostDeleteView(LoginRequiredMixin, UserPassesTestMixin, DetailView):
    model = Post
    template_name = 'community_board_app/delete_post.html'
    success_url = reverse_lazy('community_board_app:post_list')

    def test_func(self):
        post = self.get_object()
        # if self.request.user == post.author:
        if self.request.user == post.author or self.request.user.is_superuser:

            return True
        return False
    
    def post(self, request, *args, **kwargs):
        # Get the post object
        post = self.get_object()
        # Delete the post
        post.delete()
        # Redirect to the success URL
        return redirect(self.success_url)
    

class CommentDeleteView(LoginRequiredMixin, UserPassesTestMixin, DeleteView):
    model = Comment
    template_name = 'community_board_app/delete_comment.html'
    
    def get_success_url(self):
        return reverse_lazy('community_board_app:post_detail', kwargs={'slug': self.object.post.slug})
    
    def test_func(self):
        comment = self.get_object()
        return self.request.user == comment.author or self.request.user.is_staff



class CategoryListView(ListView):
    model = Category
    template_name = 'community_board_app/category_list.html'  # Specify your template
    context_object_name = 'categories'  # The variable name in the template
    ordering = ['name']  # Optional: Order categories alphabetically


class CategoryDetailView(DetailView):
    model = Category
    template_name = 'community_board_app/category_detail.html'
    context_object_name = 'category'

    def get_object(self):
        return get_object_or_404(Category, slug=self.kwargs['slug'])




class CategoryDeleteView(LoginRequiredMixin, UserPassesTestMixin, DeleteView):
    model = Category
    template_name = 'community_board_app/delete_category.html'
    success_url = reverse_lazy('community_board_app:category_list')  # Redirect to the category list after deletion

    def test_func(self):
        category = self.get_object()
        # Allow only superusers or staff to delete categories
        return self.request.user.is_superuser or self.request.user.is_staff
    
    def post(self, request, *args, **kwargs):
        # Get the category object
        category = self.get_object()
        # Delete the category
        category.delete()
        # Redirect to the success URL (category list)
        return redirect(self.success_url)

community_board_app/templates/community_board_app/components/admin_navbar.html
<nav class="bg-gray-800">
    <div class="max-w-screen-xl flex flex-wrap items-center justify-between mx-auto p-2">
        <a href="{% url 'cms_app:cms_dashboard' %}dashboard" class="flex items-center space-x-3 rtl:space-x-reverse">
            <span class="self-center font-semibold whitespace-nowrap text-white">Admin</span>
        </a>
        <button data-collapse-toggle="navbar-solid-bg" type="button"
            class="inline-flex items-center p-2 w-10 h-10 justify-center text-sm text-gray-500 rounded-lg md:hidden hover:bg-gray-100 focus:outline-none focus:ring-2 focus:ring-gray-200"
            aria-controls="navbar-solid-bg" aria-expanded="false">
            <span class="sr-only">Open main menu</span>
            <svg class="w-5 h-5" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 17 14">
                <path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2"
                    d="M1 1h15M1 7h15M1 13h15" />
            </svg>
        </button>
        <div class="hidden w-full md:block md:w-auto" id="navbar-solid-bg">
            <ul
                class="flex flex-col font-medium mt-4 rounded-lg bg-gray-50 md:space-x-8 rtl:space-x-reverse md:flex-row md:mt-0 md:border-0 md:bg-transparent">
                <li>
                    <a href="/"
                        class="block py-2 px-3 md:p-0 text-white bg-blue-500 rounded-sm md:bg-transparent md:text-gray-200"
                        aria-current="page">Home Page</a>
                </li>
                <!-- <li>
                    <a href="#"
                        class="block py-2 px-3 md:p-0 text-gray-100 rounded-sm hover:bg-gray-50 md:hover:bg-transparent md:border-0 md:hover:text-gray-200">Services</a>
                </li>
                <li>
                    <a href="#"
                        class="block py-2 px-3 md:p-0 text-gray-100 rounded-sm hover:bg-gray-50 md:hover:bg-transparent md:border-0 md:hover:text-gray-200">Pricing</a>
                </li> -->
                <li>
                    <a href="{% url 'cms_app:cms_dashboard' %}dashboard"
                        class="block py-2 px-3 md:p-0 text-gray-100 rounded-sm hover:bg-gray-50 md:hover:bg-transparent md:border-0 md:hover:text-gray-200">CMS
                        Dashboard</a>
                </li>
            </ul>
        </div>
    </div>
</nav>

community_board_app/templates/community_board_app/components/hero.html
{% if hero_settings.hero_active %}
<section class="relative pt-[4em] 2xl:pt-[3em] mb-10 max-h-[800px] min-h-[400px] bg-cover bg-center"
style="{% if hero_settings.bg_color %} background-color: {{ hero_settings.bg_color|safe }}; {% endif %}
        {% if hero_settings.text_color %} color: {{ hero_settings.text_color|safe }}; {% endif %}
        {% if hero_settings.hero_image %} background-image: url('{{ hero_settings.hero_image.url }}'); {% endif %}">

    <!-- Overlay (Fix height using h-full) -->
    {% if hero_settings.hero_image %}
    <div class="absolute top-0 left-0 w-full h-full bg-black bg-opacity-50 z-0"></div>
    {% endif %}

    <div class="relative py-4 px-4 mx-auto  text-center lg:py-16 lg:px-12 z-10">
        {% if hero_settings.h1_text %}

        <h1
            class="mb-4 text-4xl font-extrabold tracking-tight leading-none  md:text-5xl lg:text-6xl ">
            {{ hero_settings.h1_text }}</h1>
            </h1>
            {% endif %}
            {% if hero_settings.sub_text %}
        <p class="text-lg font-normal lg:text-xl sm:px-16 xl:px-48">
            {{ hero_settings.sub_text }}
        </p>
        {% endif %}
        <div class="flex flex-col mt-12 mb-2 lg:mb-10 space-y-4 sm:flex-row sm:justify-center sm:space-y-0 sm:space-x-4">
            {% if hero_settings.button_one_text %}
            <a href="{{ hero_settings.button_one_link }}"
                class="inline-flex justify-center items-center py-3 px-5 text-base font-medium text-center rounded-lg border hover:border-gray-300  hover:text-gray-300 focus:ring-4 focus:ring-primary-300">
                {{ hero_settings.button_one_text }}
                <svg class="ml-2" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="none"
                    stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" width="22" height="22"
                    stroke-width="1.75">
                    <path d="M5 12l14 0"></path>
                    <path d="M15 16l4 -4"></path>
                    <path d="M15 8l4 4"></path>
                </svg>
            </a>
            {% endif %}
            {% if hero_settings.button_two_text %}
            {% if not user.is_authenticated %}
            <a href="{{ hero_settings.button_two_link }}"
                class="inline-flex justify-center items-center py-3 px-5 text-base font-medium text-center rounded-lg border {% if hero_settings.text_color %}  border-[{{ hero_settings.text_color|safe }}] {% endif %} hover:text-gray-900 hover:bg-gray-100 hover:border-gray-100 focus:ring-4 focus:ring-gray-100">
                <svg class="mr-2" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="none"
                    stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" width="22" height="22"
                    stroke-width="1.8">
                    <path d="M8 7a4 4 0 1 0 8 0a4 4 0 0 0 -8 0"></path>
                    <path d="M16 19h6"></path>
                    <path d="M19 16v6"></path>
                    <path d="M6 21v-2a4 4 0 0 1 4 -4h4"></path>
                </svg>
                {{ hero_settings.button_two_text }}
            </a>

            {% endif %}
            {% endif %}
        </div>
        {% if hero_settings.featured_active %}
        <div class="pt-10 px-4 mx-auto text-center md:max-w-screen-md lg:max-w-screen-lg lg:px-36">
            <span class="font-semibold uppercase">FEATURED IN</span>
            <div class="flex flex-wrap justify-center items-center mt-2 sm:justify-around">
                {% if hero_settings.featured_one_icon and hero_settings.featured_one_link %}
                    <a href="{{ hero_settings.featured_one_link }}" class="mx-3 w-[130px] md:w-[180px] lg:mb-0 hover:text-gray-100">
                        <img src="{{ hero_settings.featured_one_icon.url }}" alt="Logo" class="navbar-logo">
                    </a>
                {% endif %}
                {% if hero_settings.featured_two_icon and hero_settings.featured_two_link %}
                    <a href="{{ hero_settings.featured_two_link }}" class="mx-3 w-[130px] md:w-[180px] lg:mb-0 hover:text-gray-100">
                        <img src="{{ hero_settings.featured_two_icon.url }}" alt="Logo" class="navbar-logo">
                    </a>
                {% endif %}
                {% if hero_settings.featured_three_icon and hero_settings.featured_three_link %}
                    <a href="{{ hero_settings.featured_three_link }}" class="mx-3 w-[130px] md:w-[180px] lg:mb-0 hover:text-gray-100">
                        <img src="{{ hero_settings.featured_three_icon.url }}" alt="Logo" class="navbar-logo">
                    </a>
                {% endif %}
            </div>
        </div>
    {% endif %}
    
    
    </div>
</section>
{% endif %}

community_board_app/templates/community_board_app/components/navbar.html
<nav class="bg-white border-gray-200 py-2">
    <div class="max-w-screen-xl flex flex-wrap items-center justify-between mx-auto p-4">
        <a href="{% url 'community_board_app:index' %}" class="flex items-center space-x-3 rtl:space-x-reverse">
            {% if navbar_logo %}
            <img src="{{ navbar_logo }}" width="50" alt="{{ navbar_alt_text|default:'Logo' }}" class="navbar-logo">
            {% endif %}
            <span class="self-center text-2xl font-semibold whitespace-nowrap">{{ navbar_title }}</span>
        </a>

        <div class="flex md:order-2 space-x-3 md:space-x-0 rtl:space-x-reverse">

            <button data-collapse-toggle="navbar-cta" type="button"
                class="inline-flex items-center p-2 w-10 h-10 justify-center text-sm text-gray-500 rounded-lg md:hidden hover:bg-gray-100 focus:outline-none focus:ring-2 focus:ring-gray-200"
                aria-controls="navbar-cta" aria-expanded="false">
                <span class="sr-only">Open main menu</span>
                <svg class="w-5 h-5" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="none"
                    viewBox="0 0 17 14">
                    <path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2"
                        d="M1 1h15M1 7h15M1 13h15" />
                </svg>
            </button>
        </div>
        <div class="items-center justify-end hidden w-full md:flex md:w-[66%] md:order-1" id="navbar-cta">

            <a href="{% url 'community_board_app:create_post' %}" type="button"
                class="text-white btn-color focus:ring-4 focus:outline-none focus:ring-blue-300 font-medium rounded text-md px-4 py-2 text-center :focus:ring-blue-800">
                Create Post
            </a>
            {% if user.is_authenticated %}
            <a href="{% url 'profile_app:profile' %}"
                class="font-medium rounded-lg px-4 py-2 text-center text-sm hover:text-blue-700">Profile</a>
            <a href="{% url 'account_logout' %}" class="font-medium rounded text-sm px-4 py-2 text-center">Log
                Out</a>
            {% else %}
            <a href="{% url 'account_login' %}"
                class="font-medium rounded px-4 py-2 text-center text-sm hover:text-blue-700">Log In</a>
            {% endif %}

            </ul>
        </div>
    </div>
</nav>