cms_app/urls.py
from django.urls import path
from .views import CmsUsersView,cms_overview_view, cms_view, cms_categories_view, CMSDashboardView

app_name = 'cms_app'

urlpatterns = [
    path("dashboard", cms_overview_view, name="cms_overview_view"),  # Correct name
    path('', CMSDashboardView.as_view(), name='cms_dashboard'),
    path('users', CmsUsersView.as_view(), name='cms_users_view'),
    path('settings', cms_view, name='cms_view'),
    path('categories', cms_categories_view, name='cms_categories_view'),
]

community_board_app/urls.py
from django.urls import path
from . import views
from .views import (
    IndexListView,
    PostListView, PostDetailView,
    CreatePostView, PostDeleteView,
    PostUpdateView, CommentDeleteView,
    CategoryListView, CategoryDetailView,
    CategoryDeleteView
)
app_name = 'community_board_app'

urlpatterns = [
    # path('', index, name='index'),
    path('', IndexListView.as_view(), name='index'),
    path('posts/', PostListView.as_view(), name='post_list'),
    path('create/', CreatePostView.as_view(), name='create_post'),
    path('post/<slug:slug>/', PostDetailView.as_view(), name='post_detail'),
    path('delete/<slug:slug>/', PostDeleteView.as_view(), name='delete_post'),
    path('edit/<slug:slug>/', PostUpdateView.as_view(), name='edit_post'),
    path('comment/<int:pk>/delete/', CommentDeleteView.as_view(), name='comment_delete'),
    path('categories/', CategoryListView.as_view(), name='category_list'),
    path('category/<slug:slug>/', CategoryDetailView.as_view(), name='category_detail'),
    path('delete/category/<slug:slug>/', CategoryDeleteView.as_view(), name='delete_category'),
]

community_board_project/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('profile/', include('profile_app.urls')),
    path('cms/', include('cms_app.urls')),
    path('accounts/', include('allauth.urls')),
    path('', include('community_board_app.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

cms_app/models.py
from django.db import models
from django.core.cache import cache  # Import cache
from django.core.exceptions import ValidationError
from django.utils import timezone
from django.contrib.auth.models import User

class WebsiteSettings(models.Model):
    primary_color = models.CharField(max_length=7, default="#3498db")  # Hex color
    secondary_color = models.CharField(max_length=7, default="#2c3e50")  # Hex color
    
    button_color = models.CharField(max_length=7, default="#3498db")  # Hex color
    button_text_color = models.CharField(max_length=7, default="#ffffff")  # Hex color
    button_hover_color = models.CharField(max_length=7, default="#2980b9")  # Hex color
    button_hover_text_color = models.CharField(max_length=7, default="#ffffff")  # Hex color

    def save(self, *args, **kwargs):
        if WebsiteSettings.objects.exists() and not self.pk:
            raise ValidationError("Only one instance of WebsiteSettings is allowed.")
        super().save(*args, **kwargs)
        cache.clear()  # Clear cache to apply changes instantly

    def __str__(self):
        return "Website Settings"

    class Meta:
        verbose_name = "Website Setting"
        verbose_name_plural = "Website Settings"

class NavbarSettings(models.Model):
    site_title = models.CharField(max_length=255, default="My Site")
    logo = models.FileField(upload_to='navbar_icon/', blank=True, null=True)
    alt_text = models.CharField(max_length=255, blank=True, null=True)  # Alt text for the logo
    def __str__(self):
        return "Navbar Settings"

    class Meta:
        verbose_name_plural = "Navbar Settings"


class HeroSettings(models.Model):
    hero_active = models.BooleanField(default=False)
    hero_image = models.FileField(upload_to='images/', blank=True, null=True)
    text_color = models.CharField(max_length=7, default="#ffffff")  # Default color is white
    bg_color = models.CharField(max_length=7, default="#111827") # Default color is a dark blue
    button_one_text = models.CharField(max_length=255, blank=True, null=True)
    button_one_link = models.CharField(max_length=255, blank=True, null=True)
    button_two_text = models.CharField(max_length=255, blank=True, null=True)
    button_two_link = models.CharField(max_length=255, blank=True, null=True)
    h1_text = models.CharField(max_length=255, blank=True, null=True)
    sub_text = models.CharField(max_length=255, blank=True, null=True)

    featured_active = models.BooleanField(default=False)
    featured_one_icon = models.FileField(upload_to='icons/', blank=True, null=True)
    featured_one_link = models.CharField(max_length=255, blank=True, null=True)
    featured_two_icon = models.FileField(upload_to='icons/', blank=True, null=True)
    featured_two_link = models.CharField(max_length=255, blank=True, null=True)
    featured_three_icon = models.FileField(upload_to='icons/', blank=True, null=True)
    featured_three_link = models.CharField(max_length=255, blank=True, null=True)

    def __str__(self):
        return "Hero Section Settings"

    class Meta:
        verbose_name_plural = "Hero Settings"

cms_app/forms.py
# forms.py
from django import forms
from .models import NavbarSettings, HeroSettings, WebsiteSettings


class WebsiteSettingsForm(forms.ModelForm):
    class Meta:
        model = WebsiteSettings
        fields = ['primary_color', 'secondary_color', 'button_color', 'button_hover_color',
                  'button_text_color', 'button_hover_text_color']


        widgets = {
            'primary_color': forms.TextInput(attrs={'type': 'color'}),  # Adds a color picker
            'secondary_color': forms.TextInput(attrs={'type': 'color'}),  # Adds a color picker
            'button_color': forms.TextInput(attrs={'type': 'color'}),  # Adds a color picker
            'button_text_color': forms.TextInput(attrs={'type': 'color'}),  # Adds a color picker
            'button_hover_color': forms.TextInput(attrs={'type': 'color'}),  # Adds a color picker
            'button_hover_text_color': forms.TextInput(attrs={'type': 'color'}),  # Adds a color picker
        }

        

class NavbarSettingsForm(forms.ModelForm):
    class Meta:
        model = NavbarSettings
        fields = ['site_title', 'logo', 'alt_text']

        labels = {
            'site_title': 'Site Title',
            'logo': 'Site Logo',
            'alt_text': 'Logo alt text'
        }


class HeroSettingsForm(forms.ModelForm):
    class Meta:
        model = HeroSettings
        fields = ['hero_active', 'hero_image', 'text_color', 'bg_color', 'h1_text',
                  'sub_text', 'button_one_text', 'button_one_link',
                  'button_two_text', 'button_two_link', 'featured_active',
                  'featured_one_icon', 'featured_one_link', 'featured_two_icon',
                  'featured_two_link', 'featured_three_icon', 'featured_three_link']


        labels = {
            'hero_active': 'Activeate Hero Section',
            'bg_color': 'Background Color',
            'featured_active': 'Activate Featured Section',
        }


        widgets = {
            'bg_color': forms.TextInput(attrs={'type': 'color'}),  # Adds a color picker
            'text_color': forms.TextInput(attrs={'type': 'color'}),  # Adds a color picker
        }

cms_app/views.py
from django.shortcuts import render, redirect
from django.views.generic import TemplateView
from django.http import HttpRequest
from user_visit.models import UserVisit
from django.utils.timezone import now
from django.utils import timezone
from datetime import timedelta

from cms_app.models import (
    NavbarSettings, HeroSettings,
    WebsiteSettings
    )

from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.decorators import login_required
from django.http import HttpResponseForbidden

from profile_app.models import User
from community_board_app.models import Category
from cms_app.forms import NavbarSettingsForm, HeroSettingsForm, WebsiteSettingsForm
from django.views import View
from django.urls import reverse
from django.db.models import Count



class CMSDashboardView(LoginRequiredMixin, TemplateView):
    template_name = "cms_app/cms_dashboard.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["current_view"] = self.request.resolver_match.view_name  # Get the current view name
        return context
    


@login_required
def cms_overview_view(request: HttpRequest):
    # If not authenticated, return 403 Forbidden
    if not request.user.is_authenticated:
        return HttpResponseForbidden("You do not have permission to view this page.")

    if request.headers.get('HX-Request'):
        return render(request, 'cms_app/partials/cms_overview.html')

    return render(request, 'cms_app/cms_dashboard.html', {'current_view': 'cms_overview_view'})



# CMS settings view
def cms_view(request):
    # Check if the user is authenticated, otherwise return a 403 Forbidden response
    if not request.user.is_authenticated:
        return HttpResponseForbidden("You do not have permission to view this page.")
    
    navbar_settings, created_navbar = NavbarSettings.objects.get_or_create(pk=1)
    hero_settings, created_hero = HeroSettings.objects.get_or_create(pk=1)
    website_settings, created_website = WebsiteSettings.objects.get_or_create(pk=1)

    if request.method == 'POST':
        navbar_form = NavbarSettingsForm(request.POST, request.FILES, instance=navbar_settings)
        hero_form = HeroSettingsForm(request.POST, request.FILES, instance=hero_settings)
        website_form = WebsiteSettingsForm(request.POST, request.FILES, instance=website_settings)

        if navbar_form.is_valid() and hero_form.is_valid() and website_form.is_valid():
            navbar_form.save()
            hero_form.save()
            website_form.save()

            if request.headers.get('HX-Request'):
                return render(request, 'cms_app/partials/cms_site_settings.html', {
                    'navbar_form': navbar_form,
                    'hero_form': hero_form,
                    'website_form': website_form
                })

            return redirect(reverse('cms_app:cms_dashboard'))

    else:
        navbar_form = NavbarSettingsForm(instance=navbar_settings)
        hero_form = HeroSettingsForm(instance=hero_settings)
        website_form = WebsiteSettingsForm(instance=website_settings)

    if request.headers.get('HX-Request'):
        return render(request, 'cms_app/partials/cms_site_settings.html', {
            'navbar_form': navbar_form,
            'hero_form': hero_form,
            'website_form': website_form
        })

    return render(request, 'cms_app/cms_dashboard.html', {
        'navbar_form': navbar_form,
        'hero_form': hero_form,
        'website_form': website_form,
        'current_view': 'cms_view'
    })



class CmsUsersView(LoginRequiredMixin, View):
    model = User
    paginate_by = 50 
    
    def get(self, request: HttpRequest):
        # Query all users with their related profiles
        users = User.objects.all().select_related('profile')

        # Get the current time
        now = timezone.now()

        # Check if the user is online
        for user in users:
            # Consider user online if their last_seen is within the last 5 minutes
            user.is_online = user.profile.last_seen and now - user.profile.last_seen < timedelta(minutes=5)

        # If it's an HTMX request, return only the partial template
        if request.headers.get('HX-Request'):
            return render(request, 'cms_app/partials/cms_users.html', {'users': users})

        # For normal requests, return the full dashboard template
        return render(request, 'cms_app/cms_dashboard.html', {
            'current_view': 'cms_users_view',
            'users': users,
        })


@login_required
def cms_categories_view(request: HttpRequest):
    # Annotate categories with the number of related posts
    categories = Category.objects.annotate(post_count=Count('posts'))

    # Check if the user is authenticated; if not, return 403 Forbidden
    if not request.user.is_authenticated:
        return HttpResponseForbidden("You do not have permission to view this page.")

    # Handle HTMX requests by returning only the partial template
    if request.headers.get("HX-Request"):
        return render(request, "cms_app/partials/cms_categories.html", {"categories": categories})

    # For normal requests, render the full dashboard template
    return render(
        request,
        "cms_app/cms_dashboard.html",
        {
            "current_view": "cms_categories_view",
            "categories": categories
        }
    )

cms_app/templates/cms_app/partials/cms_categories.html
<div class="max-w-screen-md mx-auto p-4">
    <h1 class="text-2xl pb-6">Categories</h1>

    {% for category in categories %}
    <ul>
        <li class="text-lg mb-4 shadow-md sm:rounded-lg bg-white/80 px-6 py-4 flex justify-between items-center">
            <div class="">
                <a href="{% url 'community_board_app:category_detail' category.slug %}">{{ category.name }}</a>
                <p class="text-sm">post: {{ category.posts.count }}</p>
            </div>
            <a class="text-red-800 bg-red-200 hover:bg-red-300 hover:text-red-900 rounded-lg text-sm px-5 py-2 text-center" href="{% url 'community_board_app:delete_category' category.slug %}">Delete</a>
        </li>
    </ul>
    {% empty %}
    <p>No categories available.</p>
    {% endfor %}
</div>

cms_app/templates/cms_app/partials/cms_overview.html
<div class="max-w-screen-md mx-auto p-4">
    <h1 class="text-2xl">Overview Page</h1>
</div>

cms_app/templates/cms_app/partials/cms_site_settings.html
{% load tailwind_filters %}

<div class="max-w-screen-md mx-auto p-4">
    <form action="{% url 'cms_app:cms_view' %}" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        <div class="shadow-md sm:rounded-lg bg-white/80 p-6">
            
            <h2 class="text-2xl mb-4">Global Color Settings</h2>
            <p>These settings will be applied to the entire site. Buttons, H1, small text (dates, author...)</p>
            <div class="grid grid-cols-1 md:grid-cols-2 gap-4 mt-4">
                {{ website_form|crispy }}
            </div>
        </div>




        <div class="mt-8 shadow-md sm:rounded-lg bg-white/80 p-6">
            <h2 class="text-2xl mb-4">Navbar Settings</h2>
            {{ navbar_form|crispy }}
        </div>

        <div class="mt-8 shadow-md sm:rounded-lg bg-white/80 p-6">
            <h2 class="text-2xl mb-4">Hero Section Settings</h2>
            {{ hero_form|crispy }}
            <button type="submit" class="mt-8 btn-color text-white px-4 py-2 rounded">Save
                Changes</button>
        </div>
    </form>
</div>

cms_app/templates/cms_app/partials/cms_users.html
{% load static %}

<div class="max-w-[120ch] mx-auto p-4">
    <div class="relative overflow-x-auto shadow-md sm:rounded-lg bg-white/80 p-8">
        <div
            class="flex items-center justify-between flex-column flex-wrap md:flex-row space-y-4 md:space-y-0 pb-4 bg-white">
            <label for="table-search" class="sr-only">Search</label>
            <div class="relative">
                <div class="absolute inset-y-0 rtl:inset-r-0 start-0 flex items-center ps-3 pointer-events-none">
                    <svg class="w-4 h-4 text-gray-500" aria-hidden="true"
                        xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 20 20">
                        <path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2"
                            d="m19 19-4-4m0-7A7 7 0 1 1 1 8a7 7 0 0 1 14 0Z" />
                    </svg>
                </div>
                <input type="text" id="table-search-users"
                    class="block p-2 ps-10 text-sm text-gray-900 border border-gray-300 rounded-lg w-80 bg-gray-50 focus:ring-blue-500 focus:border-blue-500"
                    placeholder="Search for users">
            </div>
        </div>
        <table class="w-full text-sm text-left rtl:text-right text-gray-500">
            <thead class="text-xs text-gray-700 uppercase bg-gray-50">
                <tr>
                    <th scope="col" class="px-6 py-3">
                        Name
                    </th>
                    <th scope="col" class="px-6 py-3">
                        Position
                    </th>
                    <th scope="col" class="px-6 py-3">
                        Status
                    </th>
                    <th scope="col" class="px-6 py-3">
                        Last seen
                    </th>
                    <th scope="col" class="px-6 py-3">
                        Action
                    </th>
                </tr>
            </thead>
            <tbody>
                {% for user in users %}
                <tr
                    class="bg-white border-b  border-gray-200 hover:bg-gray-50 ">

                    <th scope="row" class="flex items-center pr-6 py-4 text-gray-900 whitespace-nowrap">

                        <img class="w-12 h-12 rounded-full"
                            src="{% if user.profile.profile_picture %}{{ user.profile.profile_picture.url }}{% else %}{% static 'profile_pics/profile_image.webp' %}{% endif %}"
                            alt="{{ user.username }}'s profile picture">
                        <div class="ps-3">
                            <div class="text-base font-semibold">{{ user.username }}</div>
                            <div class="font-normal text-gray-500">{{ user.email }}</div>
                        </div>
                    </th>
                    <td class="px-6 py-4">
                        <a href="#" class="font-medium text-blue-600 hover:underline">{{ user.profile.occupation }}</a>
                    </td>
                    <td class="px-6 py-4">
                    </td>
                    <td class="px-6 py-4">
                        <p>
                            {% if user.is_authenticated %}
                                {% if user.is_online %}
                                    <!-- Green dot if the user is logged in and online -->
                                    <span class="text-green-500">●</span> <!-- Green dot for online -->
                                {% else %}
                                    <!-- Last seen if the user is authenticated but not online -->
                                    {% if user.profile.last_seen %}
                                        Last seen: {{ user.profile.last_seen|date:"F j, Y, g:i a" }}
                                    {% else %}
                                        No last seen data
                                    {% endif %}
                                {% endif %}
                            {% else %}
                                <!-- Show last seen for users who are not logged in (not authenticated) -->
                                {% if user.profile.last_seen %}
                                    Last seen: {{ user.profile.last_seen|date:"F j, Y, g:i a" }}
                                {% else %}
                                    No last seen data
                                {% endif %}
                            {% endif %}
                        </p>
                    </td>
                    
                    <td class="px-6 py-4">
                        <a href="#" class="font-medium text-blue-600 hover:underline">Edit user</a>
                    </td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>

</div>