cms_app/urls.py
from django.urls import path
from .views import CmsUsersView,cms_overview_view, cms_view, cms_categories_view, CMSDashboardView

app_name = 'cms_app'

urlpatterns = [
    path("dashboard", cms_overview_view, name="cms_overview_view"),  # Correct name
    path('', CMSDashboardView.as_view(), name='cms_dashboard'),
    path('users', CmsUsersView.as_view(), name='cms_users_view'),
    path('settings', cms_view, name='cms_view'),
    path('categories', cms_categories_view, name='cms_categories_view'),
]

community_board_app/urls.py
from django.urls import path
from . import views
from .views import (
    IndexListView,
    PostListView, PostDetailView,
    CreatePostView, PostDeleteView,
    PostUpdateView, CommentDeleteView,
    CategoryListView, CategoryDetailView,
    CategoryDeleteView
)
app_name = 'community_board_app'

urlpatterns = [
    # path('', index, name='index'),
    path('', IndexListView.as_view(), name='index'),
    path('posts/', PostListView.as_view(), name='post_list'),
    path('create/', CreatePostView.as_view(), name='create_post'),
    path('post/<slug:slug>/', PostDetailView.as_view(), name='post_detail'),
    path('delete/<slug:slug>/', PostDeleteView.as_view(), name='delete_post'),
    path('edit/<slug:slug>/', PostUpdateView.as_view(), name='edit_post'),
    path('comment/<int:pk>/delete/', CommentDeleteView.as_view(), name='comment_delete'),
    path('categories/', CategoryListView.as_view(), name='category_list'),
    path('category/<slug:slug>/', CategoryDetailView.as_view(), name='category_detail'),
    path('delete/category/<slug:slug>/', CategoryDeleteView.as_view(), name='delete_category'),
]

community_board_project/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('profile/', include('profile_app.urls')),
    path('cms/', include('cms_app.urls')),
    path('accounts/', include('allauth.urls')),
    path('', include('community_board_app.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

community_board_app/models.py
from django.db import models
from django.utils.text import slugify
from django.urls import reverse
from django.contrib.auth.models import User

class Category(models.Model):
    name = models.CharField(max_length=100, unique=True)  # Category name (e.g., "Technology", "Health")
    slug = models.SlugField(unique=True, blank=True)  # URL-friendly identifier
    description = models.TextField(blank=True, null=True)  # Optional description

    def __str__(self):
        return self.name

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(self.name)
        super().save(*args, **kwargs)

class Post(models.Model):
    DRAFT = 'draft'
    PUBLISHED = 'published'

    STATUS_CHOICES = [
        (DRAFT, 'Draft'),
        (PUBLISHED, 'Published'),
    ]

    title = models.CharField(max_length=200)
    content = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    author = models.ForeignKey('auth.User', on_delete=models.CASCADE, related_name='posts')  # Added related_name
    category = models.ForeignKey(Category, on_delete=models.SET_NULL, null=True, blank=True, related_name='posts')
    slug = models.SlugField(max_length=250, unique=True)
    status = models.CharField(max_length=10, choices=STATUS_CHOICES,default=DRAFT)

    class Meta:
        verbose_name_plural = "posts"
        ordering = ['-created_at'] 

    def save(self, *args, **kwargs):
        if not self.slug:  # Create slug only if it doesn't exist
            self.slug = slugify(self.title)
        super().save(*args, **kwargs)

    def __str__(self):
        return self.title
    
    def get_absolute_url(self):
        return reverse('community_board_app:post_detail', kwargs={'slug': self.slug})
    
    
class Comment(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE, related_name='comments')
    author = models.ForeignKey(User, on_delete=models.CASCADE)  # Assuming users are logged in
    email = models.EmailField(blank=True, null=True)
    content = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f'Comment by {self.author.username}'
    
    class Meta:
        ordering = ['created_at']

class Like(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE, related_name='likes')
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='likes')

    class Meta:
        constraints = [
            models.UniqueConstraint(fields=['post', 'user'], name='unique_post_like')
        ]

    def __str__(self):
        return f'{self.user.username} likes "{self.post.title}"'


class SiteDescription(models.Model):
    title = models.CharField(max_length=255)
    content = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    num_posts = models.PositiveIntegerField(default=0)
    num_members = models.PositiveIntegerField(default=0)


    def save(self, *args, **kwargs):
        """Ensure only one instance exists"""
        if not SiteDescription.objects.exists():
            super().save(*args, **kwargs)
        else:
            self.pk = SiteDescription.objects.first().pk
            super().save(*args, **kwargs)

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = "Site Description"
        verbose_name_plural = "Site Description"

    def num_posts(self):
        """Returns the number of published posts."""
        return Post.objects.filter(status=Post.PUBLISHED).count()

    def num_users(self):
        """Returns the total number of registered users."""
        return User.objects.count()

community_board_app/forms.py
from django import forms
from .models import Post, Comment

class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ['title', 'content', 'category','status']
        

        widgets = {
            'content': forms.Textarea(attrs={'placeholder': 'Write your post...'}),
        }


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ['content']
        
        labels = {
            'content': 'Comment'
        }

        widgets = {
            'content': forms.Textarea(attrs={'placeholder': 'Write your comment...'})
        }

community_board_app/views.py
from django.shortcuts import render
from django.http import HttpResponse
from django.http import JsonResponse
from django.views.generic import (
    DetailView, ListView,
    CreateView, DeleteView,
    UpdateView, 
)
from .models import Post, Comment, Category, SiteDescription

from django.shortcuts import get_object_or_404
from django.db.models import Count, Prefetch
from cms_app.models import HeroSettings
from .forms import PostForm, CommentForm
from django.shortcuts import redirect
from django.urls import reverse_lazy
from django.template.loader import render_to_string

from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin


from django.shortcuts import render
from django.http import HttpResponse
from django.template.loader import render_to_string


def index(request):
    return render(request, 'community_board_app/index.html')

class IndexListView(ListView):
    model = Category
    template_name = 'community_board_app/index.html'
    context_object_name = 'categories'

    def get_queryset(self):
        # Prefetch posts related to each category with status 'PUBLISHED' and annotated with comment count
        return Category.objects.prefetch_related(
            Prefetch(
                'posts',
                queryset=Post.objects.filter(status=Post.PUBLISHED).annotate(comment_count=Count('comments'))
            )
        ).all()

    def get_context_data(self, **kwargs):
        # Get the context data, which includes categories by default
        context = super().get_context_data(**kwargs)
        
        # Optionally add hero settings if needed
        context['hero_settings'] = HeroSettings.objects.first()  # Assuming only one object exists
        context['site'] = SiteDescription.objects.first()  # Fetch the single instance
        return context

class PostListView(ListView):
    model = Post
    template_name = 'community_board_app/post_list.html'
    context_object_name = 'posts'

    def get_queryset(self):
        return Post.objects.annotate(comment_count=Count('comments'))  # Ensure queryset includes comment count

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['posts'] = Post.objects.annotate(comment_count=Count('comments'))
        context['categories'] = Category.objects.all()
        context['hero_settings'] = get_object_or_404(HeroSettings, pk=1)
        return context

    def get(self, request, *args, **kwargs):
        if request.headers.get('Hx-Request'):  # HTMX request
            posts = self.get_queryset()
            html = render_to_string("community_board_app/partials/post_partial.html", {"posts": posts})  # Pass as a list
            return HttpResponse(html)

        return super().get(request, *args, **kwargs)


class CreatePostView(LoginRequiredMixin, UserPassesTestMixin, CreateView):
    model = Post
    form_class = PostForm
    template_name = 'community_board_app/post_form.html'  # Template for the form
    success_url = reverse_lazy('community_board_app:post_list')  # Redirect after success

    def test_func(self):
        user = self.request.user
        return user.is_authenticated or user.is_staff or user.is_superuser  # Allow if logged in OR is staff/superuser
    
    def form_valid(self, form):
        form.instance.author = self.request.user  # Assign the logged-in user
        self.object = form.save()
        return redirect('community_board_app:post_detail', slug=self.object.slug)  # Redirect to post detail
    

class PostDetailView(DetailView):
    model = Post
    template_name = 'community_board_app/post_detail.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        post = self.object
        context['form'] = CommentForm()
        context['comments'] = post.comments.all()  # Retrieve all comments related to the post
        return context

    def get_queryset(self):
        return Post.objects.annotate(comment_count=Count('comments'))

    def post(self, request, *args, **kwargs):
        post = self.get_object()  # Get the current post
        form = CommentForm(request.POST)
        if form.is_valid():
            # Save the comment, but don't commit it to the DB yet
            comment = form.save(commit=False)
            comment.post = post  # Link the comment to the current post
            comment.author = request.user  # Set the comment author to the current user
            comment.save()  # Now save the comment
            return redirect('community_board_app:post_detail', slug=post.slug)  # Redirect to the post's detail page

        # If the form is not valid, render the same template with errors
        return self.get(request, *args, **kwargs)


class PostUpdateView(LoginRequiredMixin, UserPassesTestMixin, UpdateView):
    model = Post
    form_class = PostForm
    template_name = 'community_board_app/edit_post.html'
    
    def test_func(self):
        post = self.get_object()
        if self.request.user == post.author:
            return True
        return False
    

class PostDeleteView(LoginRequiredMixin, UserPassesTestMixin, DetailView):
    model = Post
    template_name = 'community_board_app/delete_post.html'
    success_url = reverse_lazy('community_board_app:post_list')

    def test_func(self):
        post = self.get_object()
        # if self.request.user == post.author:
        if self.request.user == post.author or self.request.user.is_superuser:

            return True
        return False
    
    def post(self, request, *args, **kwargs):
        # Get the post object
        post = self.get_object()
        # Delete the post
        post.delete()
        # Redirect to the success URL
        return redirect(self.success_url)
    

class CommentDeleteView(LoginRequiredMixin, UserPassesTestMixin, DeleteView):
    model = Comment
    template_name = 'community_board_app/delete_comment.html'
    
    def get_success_url(self):
        return reverse_lazy('community_board_app:post_detail', kwargs={'slug': self.object.post.slug})
    
    def test_func(self):
        comment = self.get_object()
        return self.request.user == comment.author or self.request.user.is_staff



class CategoryListView(ListView):
    model = Category
    template_name = 'community_board_app/category_list.html'  # Specify your template
    context_object_name = 'categories'  # The variable name in the template
    ordering = ['name']  # Optional: Order categories alphabetically


class CategoryDetailView(DetailView):
    model = Category
    template_name = 'community_board_app/category_detail.html'
    context_object_name = 'category'

    def get_object(self):
        return get_object_or_404(Category, slug=self.kwargs['slug'])




class CategoryDeleteView(LoginRequiredMixin, UserPassesTestMixin, DeleteView):
    model = Category
    template_name = 'community_board_app/delete_category.html'
    success_url = reverse_lazy('community_board_app:category_list')  # Redirect to the category list after deletion

    def test_func(self):
        category = self.get_object()
        # Allow only superusers or staff to delete categories
        return self.request.user.is_superuser or self.request.user.is_staff
    
    def post(self, request, *args, **kwargs):
        # Get the category object
        category = self.get_object()
        # Delete the category
        category.delete()
        # Redirect to the success URL (category list)
        return redirect(self.success_url)

community_board_app/templates/community_board_app/base.html
{% load static %}
{% load tz %}
{{ form.media }}

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <script src="https://unpkg.com/htmx.org@1.9.3"></script>
    <script src="https://cdn.tailwindcss.com"></script>
    <title>Comunity Board</title>
    <link rel="stylesheet" href="{% static 'cms_app/css/style.css' %}">

    <style>
        :root {
            --primary-color: {{ primary_color }};
            --secondary-color: {{ secondary_color }};
            --button-color: {{ button_color }};
            --button-text-color: {{ button_text_color }};
            --button-hover-color: {{ button_hover_color }};
            --button-hover-text-color: {{ button_hover_text_color }};
        }
    
        .primary {
            color: var(--primary-color) !important;
        }
    
        .bg-primary {
            background-color: var(--primary-color) !important;
        }
    
        .secondary {
            color: var(--secondary-color) !important;
        }
    
        .bg-secondary {
            background-color: var(--secondary-color) !important;
        }
    
        .btn-color {
            background-color: var(--button-color) !important;
            color: var(--button-text-color) !important;
            transition: 120ms;
        }
    
        .btn-color:hover {
            background-color: var(--button-hover-color) !important;
            color: var(--button-hover-text-color) !important;
        }
    </style>
    <link rel="stylesheet" href="{% static 'cms_app/css/style.css' %}">
    <link rel="stylesheet" href="{% static 'profile_app/css/profile.css' %}">
</head>

<body class="text-gray-900">
    {% if request.user.is_staff or request.user.is_superuser %}
    {% include 'community_board_app/components/admin_navbar.html' with post=post %}
    {% endif %}

    {% include 'community_board_app/components/navbar.html' with post=post %}
    {% include 'community_board_app/components/hero.html' with post=post %}

    <div class="mx-auto max-w-[2800px]">
        {% block content %}{% endblock content %}
    </div>



    <!-- scripts -->
    <script>
        // Check if the element has been dismissed
        if (localStorage.getItem('dropdown-cta-dismissed') === 'true') {
            document.getElementById('dropdown-cta').style.display = 'none';
        }
    </script>  
</body>

</html>

community_board_app/templates/community_board_app/category_detail.html
{% extends 'community_board_app/base.html' %}

{% block content %}


<div class="pt-10 grid grid-cols-12 gap-6 max-w-screen-xl mx-auto px-2">
    <div class="col-span-12 lg:col-span-8">
        <div class="border border-gray-200 rounded p-4 mb-6">
            <div class="border-b border-gray-200 mb-4 pb-4">
                <h2 class="text-2xl mb-1">{{ category.name }}</h2>
                <p>{{ category.description }}</p>
            </div>
            {% include 'community_board_app/partials/post_partial.html' with post=post %}

        </div>

    </div>
    <aside class="col-span-12 lg:col-span-4 lg:pl-6">
        {% include 'community_board_app/partials/category_partial.html' with categories=categories %}
    </aside>
</div>
{% endblock %}

community_board_app/templates/community_board_app/category_list.html
{% extends 'community_board_app/base.html' %}


{% block content %}
<div class="pt-10 max-w-screen-xl mx-auto">
    <h1 class="text-2xl font-bold mb-4">Categories</h1>
    <ul class="list-disc pl-5">
        {% for category in categories %}
        <li class="text-lg">
            <a href="{% url 'community_board_app:category_detail' category.slug %}"
                class="text-blue-500 hover:underline">
                {{ category.name }}
            </a>
            {% if category.description %}
            <p class="text-gray-600 text-sm">{{ category.description }}</p>
            {% endif %}
        </li>
        {% endfor %}
    </ul>
</div>
{% endblock %}

community_board_app/templates/community_board_app/delete_category.html
{% extends 'community_board_app/base.html' %}

{% block content %}

<div class="post block  max-w-screen-md mx-auto p-4" data-post-id="{{ category.id }}">

    <h2 class="text-red-700 mb-8">Are you sure you want to Delete <strong>"{{ category.name }}"</strong>?</h2>

    <h2 class="text-2xl pb-2">{{ post.title }}</h2>
    <p>{{ category.description }}</p>
   
    <div class="mt-8 flex align-middle">
        <form class="" id="form" method="post">
            {% csrf_token %}
            <button type="submit"
                class="text-red-800 bg-red-200 hover:bg-red-300 hover:text-red-900 rounded-lg text-sm px-5 py-2.5 text-center inline-flex items-center dark:bg-blue-600 dark:hover:bg-blue-700 dark:focus:ring-blue-800">
                Delete
                <svg xmlns="http://www.w3.org/2000/svg" class="ml-2" viewBox="0 0 24 24" width="20" height="20"
                    fill="currentColor">
                    <path
                        d="M17 6H22V8H20V21C20 21.5523 19.5523 22 19 22H5C4.44772 22 4 21.5523 4 21V8H2V6H7V3C7 2.44772 7.44772 2 8 2H16C16.5523 2 17 2.44772 17 3V6ZM18 8H6V20H18V8ZM9 11H11V17H9V11ZM13 11H15V17H13V11ZM9 4V6H15V4H9Z">
                    </path>
                </svg>
            </button>
        </form>


    </div>

</div>


{% endblock %}

community_board_app/templates/community_board_app/delete_comment.html
{% extends 'community_board_app/base.html' %}

{% block content %}

<div class="post block max-w-screen-md mx-auto p-4" data-comment-id="{{ comment.id }}">
    <h2 class="text-red-700 mb-8">Are you sure you want to delete this comment?</h2>

    <p>{{ comment.content }}</p>
    <small>{{ comment.created_at }}</small>

    <div class="mt-8 flex items-center">
        <form id="delete-form" method="post">
            {% csrf_token %}
            <button type="submit"
                class="text-red-800 bg-red-200 hover:bg-red-300 hover:text-red-900 rounded-lg text-sm px-5 py-2.5 text-center inline-flex items-center">
                Delete
                <svg xmlns="http://www.w3.org/2000/svg" class="ml-2" viewBox="0 0 24 24" width="20" height="20"
                    fill="currentColor">
                    <path
                        d="M17 6H22V8H20V21C20 21.5523 19.5523 22 19 22H5C4.44772 22 4 21.5523 4 21V8H2V6H7V3C7 2.44772 7.44772 2 8 2H16C16.5523 2 17 2.44772 17 3V6ZM18 8H6V20H18V8ZM9 11H11V17H9V11ZM13 11H15V17H13V11ZM9 4V6H15V4H9Z">
                    </path>
                </svg>
            </button>
        </form>
        <a href="{{ request.META.HTTP_REFERER|default:'/' }}"
            class="text-gray-700 hover:text-gray-900 underline text-sm px-5 py-2.5">Cancel</a>
    </div>
</div>

{% endblock %}

community_board_app/templates/community_board_app/delete_post.html
{% extends 'community_board_app/base.html' %}

{% block content %}

<div class="post block  max-w-screen-md mx-auto p-4" data-post-id="{{ post.id }}">

    <h2 class="text-red-700 mb-8">Are you sure you want to Delete Post?</h2>

    <h2 class="text-2xl pb-2">{{ post.title }}</h2>
    <p>{{ post.content }}</p>
    <small>{{ post.created_at }}</small>

    <div class="mt-8 flex align-middle">
        <form class="" id="form" method="post">
            {% csrf_token %}
            <button type="submit"
                class="text-red-800 bg-red-200 hover:bg-red-300 hover:text-red-900 rounded-lg text-sm px-5 py-2.5 text-center inline-flex items-center dark:bg-blue-600 dark:hover:bg-blue-700 dark:focus:ring-blue-800">
                Delete
                <svg xmlns="http://www.w3.org/2000/svg" class="ml-2" viewBox="0 0 24 24" width="20" height="20"
                    fill="currentColor">
                    <path
                        d="M17 6H22V8H20V21C20 21.5523 19.5523 22 19 22H5C4.44772 22 4 21.5523 4 21V8H2V6H7V3C7 2.44772 7.44772 2 8 2H16C16.5523 2 17 2.44772 17 3V6ZM18 8H6V20H18V8ZM9 11H11V17H9V11ZM13 11H15V17H13V11ZM9 4V6H15V4H9Z">
                    </path>
                </svg>
            </button>
        </form>
        <a href="/" class="text-gray-700 hover:text-gray-900 underline text-sm px-5 py-2.5">Cancel</a>

    </div>

</div>


{% endblock %}

community_board_app/templates/community_board_app/edit_post.html
{% extends 'community_board_app/base.html' %}
{% load tailwind_filters %}

{% block content %}
<div class="max-w-screen-md mx-auto p-4">
    <h1>Edit Post</h1>
    <form method="POST" action="{% url 'community_board_app:edit_post' post.slug %}">
        {% csrf_token %}
        {{ form|crispy }}
        <button type="submit" class="bg-blue-500 text-white px-4 py-2 rounded">Post</button>

    </form>
</div>
{% endblock %}

community_board_app/templates/community_board_app/index.html
{% extends 'community_board_app/base.html' %}
{% load tailwind_filters %}

{% block content %}

<div class="pt-10 grid grid-cols-12 gap-6 max-w-screen-xl mx-auto px-2">
    <div class="col-span-12 lg:col-span-8">
        {% for category in categories %}
        <div class="border border-gray-200 rounded p-4 mb-6 max-h-[500px] overflow-y-auto">
            <div class="border-b border-gray-200 mb-4 pb-4">
                <h2 class="text-2xl mb-1 primary">
                    <a href="{% url 'community_board_app:category_detail' category.slug %}">{{category.name }}</a>
                </h2>
                <p>{{ category.description }}</p>
            </div>
            {% if category.posts.all %}
            <div class="">
                {{ post.title }}
                {% include 'community_board_app/partials/post_partial.html' with post=post %}
            </div>
            {% else %}
            <p class="primary">No posts yet in this category.</p>
            {% endif %}
        </div>
        {% empty %}
        <p class="primary">No categories available.</p>
        {% endfor %}
    </div>

    <aside class="col-span-12 lg:col-span-4 lg:pl-6">
        {% include 'community_board_app/partials/site_description_partial.html' with site=site %}
        {% include 'community_board_app/partials/category_partial.html' with categories=categories %}
    </aside>
</div>
{% endblock %}

community_board_app/templates/community_board_app/post_detail.html
{% extends 'community_board_app/base.html' %}
{% load tailwind_filters %}

{% block content %}
<div class="max-w-2xl p-6 mx-auto mb-4">

    <div class="post block" data-post-id="{{ post.id }}">
        <h2 class="text-2xl pb-2 primary">{{ post.title }}</h2>
        <p>{{ post.content }}</p>
        <div class="mt-2">
            <small class="secondary">Author: <strong>{{ post.author.username }}</strong>
                ({{ post.created_at|date:"F j, Y, g:ia" }})</small>
            <br>
            <p class="mt-2">{{ post.comment_count }} comments</p>
        </div>

        <div class="mt-6">
            <a href="{% url 'community_board_app:edit_post' slug=post.slug %}"
                class="text-gray-700 hover:bg-blue-100 font-medium rounded-lg text-sm px-5 py-2.5 text-center inline-flex items-center">
                Edit
                <svg class="ml-2" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" width="20" height="20"
                    fill="currentColor">
                    <path
                        d="M6.41421 15.89L16.5563 5.74785L15.1421 4.33363L5 14.4758V15.89H6.41421ZM7.24264 17.89H3V13.6473L14.435 2.21231C14.8256 1.82179 15.4587 1.82179 15.8492 2.21231L18.6777 5.04074C19.0682 5.43126 19.0682 6.06443 18.6777 6.45495L7.24264 17.89ZM3 19.89H21V21.89H3V19.89Z">
                    </path>
                </svg>
            </a>
            <a href="{% url 'community_board_app:delete_post' slug=post.slug %}"
                class="text-red-700  hover:bg-red-100 font-medium rounded-lg text-sm px-5 py-2.5 text-center inline-flex items-center">
                Delete
                <svg class="ml-2" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" width="20" height="20"
                    fill="currentColor">
                    <path
                        d="M17 6H22V8H20V21C20 21.5523 19.5523 22 19 22H5C4.44772 22 4 21.5523 4 21V8H2V6H7V3C7 2.44772 7.44772 2 8 2H16C16.5523 2 17 2.44772 17 3V6ZM18 8H6V20H18V8ZM9 11H11V17H9V11ZM13 11H15V17H13V11ZM9 4V6H15V4H9Z">
                    </path>
                </svg>
            </a>
        </div>

    </div>


    <div class="mt-8">
        <p>Discussion:</p>

        {% include 'community_board_app/partials/comment_partial.html' with post=post form=form %}

    </div>
</div>
{% endblock %}

community_board_app/templates/community_board_app/post_form.html
{% extends 'community_board_app/base.html' %}
{% load tailwind_filters %}

{% block content %}
<div class="post block  max-w-screen-md mx-auto p-4">
    <form method="post" action="{% url 'community_board_app:create_post' %}">
        {% csrf_token %}
        {{ form|crispy }}
        <button type="submit" class="btn-color px-4 py-2 rounded">Create Post</button>
    </form>
</div>
{% endblock %}

community_board_app/templates/community_board_app/post_list.html
{% extends 'community_board_app/base.html' %}
{% load tailwind_filters %}

{% block content %}
<!-- Display existing posts -->
<div class="pt-10 grid grid-cols-12 gap-6 max-w-screen-xl mx-auto px-2">

    <div class="col-span-12 lg:col-span-8" id="post-list" hx-get="{% url 'community_board_app:post_list' %}"
        hx-trigger="every 5s" hx-target="#post-list" hx-swap="innerHTML">
        {% include 'community_board_app/partials/post_partial.html' with post=post %}
    </div>
    <!-- Sidebar with Categories -->
    <aside class="col-span-12 lg:col-span-4 lg:pl-6">
        {% include 'community_board_app/partials/category_partial.html' with categories=categories %}
    </aside>
</div>
{% endblock %}